# Generated by Django 4.2 on 2023-04-15 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=30)),
                ('ism', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('brend', models.CharField(max_length=20)),
                ('narx', models.CharField(max_length=30)),
                ('kelgan_sana', models.DateField()),
                ('miqdor', models.IntegerField()),
                ('olchov', models.CharField(max_length=30)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('qarz', models.CharField(max_length=20)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.ombor')),
            ],
        ),
    ]
